# Generated by Django 2.2.23 on 2021-06-25 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookhistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bookhistory',
            name='time',
        ),
        migrations.AddField(
            model_name='bookhistory',
            name='rent_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='bookhistory',
            name='rent_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookhistory',
            name='return_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='bookhistory',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
