# Generated by Django 2.2.23 on 2021-06-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20210625_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhistory',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
